version: "3"
#Development docker compose file
services:
  database:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "${LOCAL_DB_PORT}:3306"
    restart: "no"
    container_name: "${PRODUCTION_NAME}_db"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_USER: "${LOCAL_DB_USER}"
      MYSQL_DATABASE: "${LOCAL_DB_NAME}"
      MYSQL_PASSWORD: "${LOCAL_DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${LOCAL_DB_ROOT_PASS}"

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: "${PRODUCTION_NAME}_wordpress"
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    restart: "no"
    volumes:
      - ./public:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${LOCAL_DB_HOST}:3306"
      WORDPRESS_DB_PASSWORD: "${LOCAL_DB_PASS}"

  wordmove:
    # build:
    #   context: ./wordmove
    image: welaika/wordmove
    tty: true
    depends_on:
      - wordpress
    restart: "no"
    container_name: "${PRODUCTION_NAME}_wordmove"
    volumes:
      - ./public:/html/
      #This will eventually break... waiting on solution https://github.com/welaika/wordmove/issues/581
      #- ./config/default.rb:/usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/sql_adapter/default.rb
      #Had to add .to_s to php_escape because an int was being passed in.
      #- ./config/ftp.rb:/usr/local/bundle/gems/wordmove-5.0.2/lib/wordmove/deployer/ftp.rb
      #Fix for insecure ftp requests
      # - ./config/lftp.conf:/etc/lftp.conf
    environment:
      LOCAL_SERVER_PORT: "${LOCAL_SERVER_PORT}"
      STAGING_HOST: "${STAGING_HOST}"
      STAGING_WORDPRESS_PATH: "${STAGING_WORDPRESS_PATH}"
      STAGING_DB_NAME: "${STAGING_DB_NAME}"
      STAGING_DB_USER: "${STAGING_DB_USER}"
      STAGING_DB_PASS: "${STAGING_DB_PASS}"
      STAGING_DB_HOST: "${STAGING_DB_HOST}"
      STAGING_DB_PORT: "${STAGING_DB_PORT}"
      STAGING_SSH_HOST: "${STAGING_SSH_HOST}"
      STAGING_SSH_USER: "${STAGING_SSH_USER}"
      STAGING_SSH_PASS: "${STAGING_SSH_PASS}"
      PROD_HOST: "${PROD_HOST}"
      PROD_WORDPRESS_PATH: "${PROD_WORDPRESS_PATH}"
      PROD_DB_NAME: "${PROD_DB_NAME}"
      PROD_DB_USER: "${PROD_DB_USER}"
      PROD_DB_PASS: "${PROD_DB_PASS}"
      PROD_DB_HOST: "${PROD_DB_HOST}"
      PROD_DB_PORT: "${PROD_DB_PORT}"
      PROD_SSH_HOST: "${PROD_SSH_HOST}"
      PROD_SSH_USER: "${PROD_SSH_USER}"
      PROD_SSH_PASS: "${PROD_SSH_PASS}"

  # phpmyadmin:
  #   depends_on:
  #     - database
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "${LOCAL_PORT_DB_GUI}:80"
  #   restart: "no"
  #   container_name: "${PRODUCTION_NAME}_phpmyadmin"
  #   environment:
  #     PMA_HOST: "${PMA_HOST}"

  # composer:
  #   image: composer:1.10
  #   tty: true

  #   volumes:
  #     - ./public:/app
  #   container_name: "${PRODUCTION_NAME}_composer"
